# fly.toml app configuration file generated for rentorbuy on 2025-03-12T11:18:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rentorbuy'
primary_region = 'nrt'

[build]

[processes]
  app = 'node ./dbsetup.js && npm run start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[[services]]
  internal_port = 5000
  protocol = "tcp"
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
